const path = require('path');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
let wxApis = [
    "request",
    "downloadFile",
    "uploadFile",
    "addNativeDownloadTask",
    "calRqt",
    "connectSocket",
    "closeSocket",
    "sendSocketMessage",
    "onSocketOpen",
    "onSocketClose",
    "onSocketMessage",
    "onSocketError",
    "getNetworkType",
    "onNetworkStatusChange",
    "openDocument",
    "setStorage",
    "setStorageSync",
    "getStorage",
    "getStorageSync",
    "getStorageInfo",
    "getStorageInfoSync",
    "removeStorage",
    "removeStorageSync",
    "clearStorage",
    "clearStorageSync",
    "authorize",
    "checkSession",
    "getUserInfo",
    "login",
    "openSetting",
    "getSetting",
    "sendGroupMessage",
    "reportGroupShare",
    "operateWXData",
    "getWeRunData",
    "uploadWeRunData",
    "addWeRunData",
    "getGroupMsgTicket",
    "removeUserCloudStorage",
    "setUserCloudStorage",
    "openCustomerServiceConversation",
    "sendRedPacket",
    "openRedPacket",
    "sendBizRedPacket",
    "reportAnalytics",
    "reportMonitor",
    "requestSubscribeMessage",
    "addCard",
    "openCard",
    "saveFile",
    "getFileInfo",
    "getSavedFileList",
    "getSavedFileInfo",
    "removeSavedFile",
    "readFile",
    "writeFile",
    "access",
    "unlink",
    "stat",
    "mkdir",
    "readdir",
    "rmdir",
    "getFileSystemManager",
    "startAccelerometer",
    "stopAccelerometer",
    "onAccelerometerChange",
    "startCompass",
    "stopCompass",
    "onCompassChange",
    "startDeviceMotionListening",
    "stopDeviceMotionListening",
    "onDeviceMotionChange",
    "startGyroscope",
    "stopGyroscope",
    "onGyroscopeChange",
    "setScreenBrightness",
    "getScreenBrightness",
    "setKeepScreenOn",
    "captureScreen",
    "vibrateShort",
    "vibrateLong",
    "getClipboardData",
    "setClipboardData",
    "getLocation",
    "createInnerAudioContext",
    "getAvailableAudioSources",
    "setInnerAudioOption",
    "getRecorderManager",
    "chooseImage",
    "previewImage",
    "saveImageToPhotosAlbum",
    "joinVoIPChat",
    "exitVoIPChat",
    "updateVoIPChatMuteConfig",
    "onVoIPChatMembersChanged",
    "onVoIPChatSpeakersChanged",
    "onVoIPChatInterrupted",
    "createCanvas",
    "createImage",
    "onTouchStart",
    "offTouchStart",
    "onTouchMove",
    "offTouchMove",
    "onTouchEnd",
    "offTouchEnd",
    "onTouchCancel",
    "offTouchCancel",
    "onKeyboardInput",
    "offKeyboardInput",
    "onKeyboardConfirm",
    "offKeyboardConfirm",
    "onKeyboardComplete",
    "offKeyboardComplete",
    "onWindowResize",
    "offWindowResize",
    "getShareInfo",
    "showShareMenu",
    "hideShareMenu",
    "updateShareMenu",
    "onShareAppMessage",
    "offShareAppMessage",
    "shareAppMessage",
    "showUpdatableMessageSubscribeButton",
    "setTopBarText",
    "showToast",
    "hideToast",
    "showLoading",
    "hideLoading",
    "showModal",
    "showActionSheet",
    "setMenuStyle",
    "setStatusBarStyle",
    "getMenuButtonBoundingClientRect",
    "hideSplashScreen",
    "onError",
    "offError",
    "onLaunch",
    "offLaunch",
    "onShow",
    "offShow",
    "onHide",
    "offHide",
    "onStickyStatusChange",
    "offStickyStatusChange",
    "onAudioInterruptionBegin",
    "offAudioInterruptionBegin",
    "onAudioInterruptionEnd",
    "offAudioInterruptionEnd",
    "getSystemInfo",
    "getSystemInfoSync",
    "getBatteryInfo",
    "getBatteryInfoSync",
    "getLaunchOptionsSync",
    "setPreferredFramesPerSecond",
    "loadFont",
    "getTextLineHeight",
    "requestMidasPayment",
    "gameLoginReport",
    "gameLogoutReport",
    "exitMiniProgram",
    "showKeyboard",
    "hideKeyboard",
    "updateKeyboard",
    "encode",
    "decode",
    "parseXML",
    "createVideo",
    "onDeviceOrientationChange",
    "offDeviceOrientationChange",
    "postMessage",
    "onMessage",
    "getOpenDataContext",
    "createUserGameData",
    "updateUserGameData",
    "getPerformance",
    "setEnableDebug",
    "triggerGC",
    "onMemoryWarning",
    "createWorker",
    "checkIsUserAdvisedToRest",
    "getUpdateManager",
    "getAd",
    "openTencentGameContract",
    "openTencentPrivacyContract",
    "openUrl",
    "openTencentBoardGameContract",
    "createRewardedVideoAd",
    "createIncentiveVideoAd",
    "createBannerAd",
    "createUserInfoButton",
    "createGameClubButton",
    "createOpenSettingButton",
    "createFeedbackButton",
    "loadSubpackage",
    "navigateToMiniProgram",
    "env",
    "USER_DATA_PATH",
    "getLogManager",
    "cloud",
    "init",
    "callFunction",
    "uploadFile",
    "downloadFile",
    "getTempFileURL",
    "deleteFile",
    "database",
    "version",
    "updateTime",
    "version",
    "model",
    "pixelRatio",
    "windowWidth",
    "windowHeight",
    "system",
    "language",
    "version",
    "screenWidth",
    "screenHeight",
    "SDKVersion",
    "brand",
    "fontSizeSetting",
    "benchmarkLevel",
    "batteryLevel",
    "statusBarHeight",
    "deviceOrientation",
    "platform",
    "devicePixelRatio"
];
let events = [
    'changedTouches',
    'timeStamp',
    'touches',
    'type'
];
let requestParas = [
    'url',
    'data',
    'method',
    'header',
    'success',
    'fail',
    'game_id',
    'game_key',
    'game_name',
    'game_ver',
    'offer_id',
    'time',
    'timeZone',
    'game_config',
    'public_data',
    'content',
    'msg',
    'ret',
    'res',
    'code',
    "authorize_code",
    "union_app_id",
    "time",
    "scope",
    "sign",
    'errMsg',
];
let JsonParams = [
    'stringify',
    'parse'
];
let commonParams = [
    "channel_platform",
    "ad_id",
    "device",
    "screen_width",
    "screen_height",
    "device_name",
    "os_ver",
    "sdk_ver",
    "package_name",
    "os_type",
    "net_type",
    "brand",
    "model",
    "battery_level",
    "screen_brightness",
    "game",
    "game_name",
    "game_id",
    "game_ver",
    "other",
    "client_ts",
    "client_time_zone",
    "verify",
    "event",
    "x",
    "y",
    "channel_platform",
    "ad_id",
    "device",
    "screen_width",
    "screen_height",
    "device_name",
    "os_ver",
    "sdk_ver",
    "package_name",
    "os_type",
    "net_type",
    "brand",
    "model",
    "battery_level",
    "screen_brightness",
    "game",
    "game_name",
    "game_id",
    "game_ver",
    "other",
    "client_ts",
    "client_time_zone",
    "verify",
    "open_id",
    "open_key",
    "flag",
    "sign"
];
let except = [];
const getObjectKeys = function (obj) {
    for (let key in obj) {
        except.push(key);
        let val = obj[key];
        if (val.constructor === Object) {
            getObjectKeys(val);
        }
    }
};

const reservedArr = ['require', 'exports', 'module']
    .concat(wxApis)
    .concat(events)
    .concat(requestParas)
    .concat(JsonParams)
    .concat(commonParams);

module.exports = {
    entry: './src/sdk.js',
    output: {
        filename: 'sdk.js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['env']
                    }
                }
            }]
    },
    plugins: [
        new UglifyJsPlugin(),
    ],
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                uglifyOptions: {
                    parse: {
                        // parse options
                    },
                    sourceMap: {
                        filename: "sdk.js",
                        url: "sdk.js.map"
                    },
                    compress: {
                        // compress options
                        keep_fargs: true,
                        keep_fnames: true,              // 通过true以防止压缩器丢弃函数名称。对于依赖的代码很有用
                        global_defs: {
                            // "console.log": "alert"
                        },
                        unsafe_proto: true,             //优化表达式如 Array.prototype.slice.call(a)into[].slice.call(a)
                        unsafe_regexp: true,            //启用变量替换 RegExp值的方式与常量相同。
                        unsafe_math: true,              //优化数值表达式，例如 2 * x * 3into 6 * x，可能会得出不精确的浮点结果。
                        unsafe_Function: true,          //当args和code均为字符串文字时，进行压缩和修饰
                        unsafe_comps: true,             //压缩表达式，例如a <= b假设任何操作数都不能（强制）NaN。
                    },
                    mangle: {
                        // mangle options
                        toplevel: true,

                        properties: {
                            builtins: false,
                            keep_quoted: false,
                            reserved: reservedArr,
                        }
                    },
                    output: {
                        // output options
                        ascii_only: true,
                        beautify: false,        // 代码美化
                        braces: true,
                        comments: false,   //传递true或"all"保留所有注释，"some"保留一些注释，正则表达式字符串（例如/^!/）或函数。
                        quote_keys: true,
                        quote_style: 0,
                    },
                    nameCache: null, // or specify a name cache object
                    ie8: false,
                    warnings: false,
                },
                test: /\.js(\?.*)?$/i,
                chunkFilter: function (chunk) {
                    console.log(chunk);
                    return true
                },
                cache: true,   //是否启用文件缓存，默认缓存在node_modules/.cache/uglifyjs-webpack-plugin.目录
                parallel: true,  //使用多进程并行运行来提高构建速度

            }),
        ],
    },
};
